--- 
- 
  become: true
  become_user: root
  gather_facts: true
  hosts: 127.0.0.1
  tasks: 
    - name: Install sshpass
      apt:
        name: sshpass
        state: latest
        update_cache: yes
    - name: Creates directory
      file:
        path: /root/.kube/
        state: directory
    - name: Copy file to host
      command: "{{ item }}"
      with_items:
        - touch /root/.kube/config
        - sshpass -p {{ ssh_password }} scp -o "StrictHostKeyChecking no" /root/.kube/config root@183.91.11.21:/data/recordings/ansible-config/"{{ config_name }}"
